export const arr =[
    {key:"Cat and Ghosts",value:"Paka na Mizimu"},
    {key:"shooting gallery",value:"nyumba ya sanaa ya risasi"},
    // {key:"Cat and Ghosts",value:"Paka na Mizimu"},
    {key:"Nukkad Cricket",value:"Kriketi ya Nukkad"},
    {key:"Tetris Cube",value:"Mchemraba wa Tetris"},
    {key:"Christmas Panda Run",value:"Mbio za Panda za Krismasi"},
    {key:"SuDoKu",value:"SuDoKu"},
    {key:"christmas adventure",value:"tukio la Krismasi"},
    {key:"Nature Strikes Back",value:"Asili Hupiga Nyuma"},
    {key:"Super Cowboy Run",value:"Mbio za Super Cowboy"},
    {key:"Foodie match",value:"Mechi ya Foodie"},
    {key:"Ice Cream Memory",value:"Kumbukumbu ya Ice Cream"},
    {key:"Jigsaw Puzzle",value:"Jigsaw Puzzle"},
    {key:"Lucky Wheels",value:"Magurudumu ya Bahati"},
    {key:"Math Rush",value:"Math Rush"},
    {key:"Pops Billiards",value:"Pops Billiards"},
    {key:"Quiz Game",value:"Mchezo wa Maswali"},
    {key:"safe-avoid",value:"salama-epuka"},
    {key:"Poker",value:"Poka"},
    {key:"BlueBlox2",value:"BlueBlox2"},
    {key:"Blocker",value:"Kizuiaji"},
    {key:"Happy haloween",value:"Furaha ya halloween"},
    {key:"Air Warfare",value:"Vita vya Ndege"},
    {key:"Traffic command",value:"Amri ya trafiki"},
    {key:"Mad Scientist",value:"Mwanasayansi Mwendawazimu"},
    {key:"Santa Run",value:"Mbio za Santa"},
    {key:"Angry cat school",value:"Shule ya paka hasira"},
    {key:"Handless Millionaire",value:"Milionea asiye na mikono"},
    {key:"Stack Jump",value:"Rukia Stack"},
    {key:"Gold miner",value:"Mchimbaji dhahabu"},
    {key:"Pool 8 Ball",value:"Dimbwi la Mpira 8"},
    {key:"Clash of battles",value:"Mgongano wa vita"},
    {key:"Find a Pair Animals",value:"Tafuta Wanyama Jozi"},
    {key:"Puzzle for kids",value:"Puzzle kwa watoto"},
    {key:"Math Pop",value:"Picha ya Hisabati"},
    {key:"Wood Slide",value:"Slaidi ya Mbao"},
    {key:"Terror-Shooter",value:"Mshambuliaji wa Kigaidi"},
    {key:"Stick Panda",value:"Fimbo Panda"},
    {key:"Silly Bombs",value:"Mabomu ya Kipumbavu"},
    {key:"shooting gallery",value:"nyumba ya sanaa ya risasi"},
    {key:"Shoot Robbers",value:"Risasi Majambazi"},
    {key:"Scary Run",value:"Kukimbia kwa Kutisha"},
    {key:"Save Planet",value:"Okoa Sayari"},
    {key:"samup",value:"sampu"},
    {key:"Robber Run",value:"Mbio za Jambazi"},
    {key:"Road Racer",value:"Mbio za Barabarani"},
    {key:"ranger vs zombies",value:"mgambo dhidi ya Riddick"},
    {key:"Rail Rush",value:"Kukimbilia kwa Reli"},
    {key:"Piggy Roll",value:"Piggy Roll"},
    {key:"Panic Drop",value:"Hofu Kushuka"},
    {key:"Ninja Run",value:"Mbio za Ninja"},
    {key:"Launcher",value:"Kizindua"},
    {key:"Hell On Duty",value:"Hell On Duty"},
    {key:"Great Air Battles",value:"Mapigano Makuu ya Hewa"},
    {key:"Goof Runner",value:"Mkimbiaji wa Goof"},
    {key:"Ghost-Dropper",value:"Ghost-Dropper"},
    {key:"Fruity snake",value:"Nyoka mwenye matunda"},
    {key:"Flapcat Steampunk",value:"Flapcat Steampunk"},
    {key:"Escape",value:"Kutoroka"},
    {key:"Dragon Jump",value:"Joka Rukia"},
    {key:"Dont Touch the Hooks",value:"Usiguse Kulabu"},
    {key:"Dices jump",value:"Kete zinaruka"},
    {key:"Dark Village",value:"Kijiji cha Giza"},
    {key:"Crazy Car",value:"Gari la Kichaa"},
    {key:"Chess Tower",value:"Mnara wa Chess"},
    {key:"Arcade ",value:"Ukumbi wa michezo"},
    {key:"Puzzle",value:"Fumbo"},
    {key:"Racing",value:"Mashindano ya mbio"},
    {key:"Action",value:"Kitendo"},
    {key:"Funny",value:"Mapenzi"},
    {key:"Sports",value:"Michezo"},
    {key:"Adventure",value:"Adventure"},
    {key:"Kids",value:"Watoto"}
]